# -*- coding: utf-8 -*-
sudo: true
dist: trusty
addons:
  apt:
    packages:
      - "enchant"
      - "graphviz"
      - "pdf2svg"
      - "texlive-full"
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install docutils
  - pip install tox-travis
script: tox
