# -*- coding: utf-8 -*-
sudo: true
dist: precise
addons:
  apt:
    sources:
      - sourceline: 'ppa:texlive-backports/ppa'
    packages:
      - "enchant"
      - "pgf"
      - "texlive-base"
      - "texlive-generic-recommended"
      - "texlive-generic-extra"
      - "texlive-latex-recommended"
      - "texlive-latex-extra"
      - "texlive-fonts-recommended"
      - "texlive-fonts-extra"
      - "texlive-xetex"
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install docutils
  - pip install tox-travis
script: tox
